/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package pricing

type CurrencyCode string

const (
	AFN CurrencyCode = "AFN"
	ALL CurrencyCode = "ALL"
	DZD CurrencyCode = "DZD"
	USD CurrencyCode = "USD"
	EUR CurrencyCode = "EUR"
	AOA CurrencyCode = "AOA"
	XCD CurrencyCode = "XCD"
	ARS CurrencyCode = "ARS"
	AMD CurrencyCode = "AMD"
	AWG CurrencyCode = "AWG"
	AUD CurrencyCode = "AUD"
	AZN CurrencyCode = "AZN"
	BSD CurrencyCode = "BSD"
	BHD CurrencyCode = "BHD"
	BDT CurrencyCode = "BDT"
	BBD CurrencyCode = "BBD"
	BYN CurrencyCode = "BYN"
	BZD CurrencyCode = "BZD"
	XOF CurrencyCode = "XOF"
	BMD CurrencyCode = "BMD"
	BTN CurrencyCode = "BTN"
	INR CurrencyCode = "INR"
	BOB CurrencyCode = "BOB"
	BOV CurrencyCode = "BOV"
	BAM CurrencyCode = "BAM"
	BWP CurrencyCode = "BWP"
	NOK CurrencyCode = "NOK"
	BRL CurrencyCode = "BRL"
	KYD CurrencyCode = "KYD"
	CRC CurrencyCode = "CRC"
	COP CurrencyCode = "COP"
	KMF CurrencyCode = "KMF"
	CDF CurrencyCode = "CDF"
	XAF CurrencyCode = "XAF"
	NZD CurrencyCode = "NZD"
	DKK CurrencyCode = "DKK"
	DJF CurrencyCode = "DJF"
	DOP CurrencyCode = "DOP"
	EGP CurrencyCode = "EGP"
	SVC CurrencyCode = "SVC"
	ERN CurrencyCode = "ERN"
	ETB CurrencyCode = "ETB"
	FKP CurrencyCode = "FKP"
	FJD CurrencyCode = "FJD"
	HNL CurrencyCode = "HNL"
	HKD CurrencyCode = "HKD"
	HUF CurrencyCode = "HUF"
	ISK CurrencyCode = "ISK"
	IDR CurrencyCode = "IDR"
	IRR CurrencyCode = "IRR"
	IQD CurrencyCode = "IQD"
	ILS CurrencyCode = "ILS"
	JMD CurrencyCode = "JMD"
	JPY CurrencyCode = "JPY"
	JOD CurrencyCode = "JOD"
	KZT CurrencyCode = "KZT"
	KES CurrencyCode = "KES"
	KPW CurrencyCode = "KPW"
	KRW CurrencyCode = "KRW"
	KWD CurrencyCode = "KWD"
	KGS CurrencyCode = "KGS"
	LAK CurrencyCode = "LAK"
	LBP CurrencyCode = "LBP"
	LSL CurrencyCode = "LSL"
	ZAR CurrencyCode = "ZAR"
	LRD CurrencyCode = "LRD"
	LYD CurrencyCode = "LYD"
	CHF CurrencyCode = "CHF"
	MGA CurrencyCode = "MGA"
	MWK CurrencyCode = "MWK"
	MYR CurrencyCode = "MYR"
	MVR CurrencyCode = "MVR"
	MZN CurrencyCode = "MZN"
	MXN CurrencyCode = "MXN"
	PEN CurrencyCode = "PEN"
	PHP CurrencyCode = "PHP"
	PLN CurrencyCode = "PLN"
	PAB CurrencyCode = "PAB"
	QAR CurrencyCode = "QAR"
	RON CurrencyCode = "RON"
	RUB CurrencyCode = "RUB"
	RWF CurrencyCode = "RWF"
	SCR CurrencyCode = "SCR"
	SGD CurrencyCode = "SGD"
	SLE CurrencyCode = "SLE"
	SEK CurrencyCode = "SEK"
	TJS CurrencyCode = "TJS"
	TND CurrencyCode = "TND"
	TRY CurrencyCode = "TRY"
	UYU CurrencyCode = "UYU"
	UZS CurrencyCode = "UZS"
	VUV CurrencyCode = "VUV"
	VND CurrencyCode = "VND"
	XAU CurrencyCode = "XAU"
	XAG CurrencyCode = "XAG"
	ZMW CurrencyCode = "ZMW"
	ZWL CurrencyCode = "ZWL"
)
